### ISSUE TITLE
Doesn't work with scrbook

### ISSUE THREAD

**Issue by unruhschuh** [PierreSenellart/apxproof#10]
This package does not work with \documentclass{scrbook}. The first problem is that \refname is \bibname in scrbook, but only changing that doesn't seem to be sufficient to make it work.

**Comment by PierreSenellart** [comment]
Thanks for the bug report. I have fixed the `\refname` vs `\bibname` issue in 11bae77; the example document provided with apxproof now compiles when using the `scrbook` document class.

Can you let me know if this works for you, or if there are still remaining issues? If so, I would appreciate an example (possibly minimal) where the compilation fails.

You can download the latest development version of the package from https://raw.githubusercontent.com/PierreSenellart/apxproof/develop/apxproof.sty

**Comment by PierreSenellart** [comment]
Closing this issue as the main problem identified, \refname vs \bibname, was fixed in 11bae77, incorporated into version 1.0.6. Do not hesitate to open a new bug if there are other compilation issues.
