### ISSUE TITLE
Enhancement: Provide a hyperlink from the main-text theorem to the repeated theorem.

### ISSUE THREAD

**Issue by kbauer** [PierreSenellart/apxproof#13]
Currently, when using a ``\theoremrep`` environment with ``hyperref``, a link from the repeated theorem in the appendix is created, that points to the theorem in the main text.

For navigation, it would be useful for the opposite to be true too. The most obvious place for such a link would be the numbering of the theorem (like the link from appendix to main text), allowing quickly switching between main text context and appendix.

**Comment by kbauer** [comment]
I looked into this myself over the weekend. It doesn't seem like there is any mechanism, that can reformat the main-text theorem number to contain a a hyperlink.

Trying to redefine ``\theNAME`` inserts the hyperlink in the main text, but also breaks all `\ref`s to that theorem, including the `\ref{axp@r\roman{axp@rpcounter}}` written into the `\axp@proofsfile`.

**Comment by kbauer** [comment]
I did figure out a method and implemented it (see https://github.com/kbauer/apxproof/commit/7e541bab6c70428319bba9529b1362d03359d295).

**Comment by PierreSenellart** [comment]
Thanks again for implementing this, the pull request has been merged in commit ea6c1ac.

**Comment by PierreSenellart** [comment]
Unfortunately, the forward linking feature seems to make reference to Theorems less robust. Please see the example below:

```tex
\documentclass{scrartcl}

\usepackage{apxproof}
\usepackage{hyperref}

\newtheoremrep{theorem}{Theorem}

\begin{document}
\tableofcontents

\begin{theoremrep}
  \label{thm:foo}
  Foo
\end{theoremrep}

\begin{toappendix}
  \section{Proof of Theorem~\ref{thm:foo}}
\end{toappendix}
\end{document}
```

It does compile (and works properly) on versions of apxproof before the introduction of the forward linking mechanism, but does not with the forward linking mechanism. Any idea why? I will investigate myself also, but if you see an obvious fix, let me know.

**Comment by kbauer** [comment]
Looks like `\ifboolexpr` wasn't behaving as I'd expect for some reason. If I replace
```
    \ifboolexpr{bool {axp@forward} and test {\ifcsdef{hyperlink}}}{%
      \hyperlink{#1}{#2}%
    }{%
      #2%
    }%
```
by
```
    \ifbool{axp@forward}{%
      \ifcsdef{hyperlink}{%
        \hyperlink{#1}{#2}%
      }{%
        #2%
      }
    }{%
      #2%
    }%
```
the issue goes away, even though the two snippets should be doing exactly the same.

**Comment by PierreSenellart** [comment]
Thanks! The fix works.
