### ISSUE TITLE
Equations inside repeated theorems override \labels from the main text.

### ISSUE THREAD

**Issue by kbauer** [PierreSenellart/apxproof#16]
The `\label` of equations is repeated in the appendix, if `amsmath` is loaded.
As a consequence, all `\ref`s to equations in `foobarrep` environment incorrectly refer to the appendix.

## Notes
 - The error doesn't become visible until the second compilation pass.
 - `apxproof` already redefines `\label` to `\@gobble`.
 - `amsmath` environments, including the redefined `equation`, redefines `\label` to `\label@in@display`,
    which invokes `\ltx@label`, which is defined as `\let\ltx@label\label` in `amsmath.dtx`.

## Possible solution
  - Redefine `\let\label@in@display\@gobble`, same as with `\label`, in the repetitions.

## Example

```
\documentclass{article}                        %
                                               %
\usepackage{apxproof}                          %
\usepackage{amsmath}                           % if amsmath is disabled,
\newtheoremrep{foobar}{FooBar}                 % the references are correct
                                               %
\begin{document}                               %
                                               %
\begin{foobar}                                 %
  \begin{equation}                             %
    References~to~this~equation~are~correct.   %
    \label{eq:correct}                         %
  \end{equation}                               %
\end{foobar}                                   %
                                               %
\begin{foobarrep}
  \begin{equation}
    References~here~are~broken.
    \label{eq:broken}
  \end{equation}
\end{foobarrep}

\begin{center}
  \begin{tabular}{lcc}
             & \texttt{eq:correct}    & \texttt{eq:broken} \\
    Expected & Eq.~(1)                & Eq.~(2) \\
    Obtained & Eq.~(\ref{eq:correct}) & Eq.~(\ref{eq:broken})
  \end{tabular}
\end{center}

\end{document}
```

![image](https://user-images.githubusercontent.com/7498468/42238679-f9e1b69e-7f01-11e8-94e2-e165eeafca17.png)

**Comment by PierreSenellart** [comment]
Thanks for the fix, this is simple enough. Merged in 926c39b.
