### ISSUE TITLE
Not compatible with \dump precompilation

### ISSUE THREAD

**Issue by kbauer** [PierreSenellart/apxproof#19]
LaTeX has a mechanism, where preambles can be precompiled for faster subsequent compilation, that can be summarized as 

  - Create a separate file ``document_preamble.tex``.
  - Compile it with `pdflatex -ini "&pdflatex" "document_preamble" "\\dump"` creating a `document_preamble.fmt` binary dump of several megabytes.
  - In `document.tex`, load this "format" file by starting the file with `%&document_preamble`. Otherwise it is compiled with `pdflatex document` as usual.

## Expected behavior

  - During compilation of the preamble, no `.axp` file should be created.
  - When compiling `document.tex`, `document.axp` should be created.

## Actual behavior

  - During compilation of the preamble, `document_preamble.axp` is created.
  - When compiling `document.tex`, no `.axp` file is created, leading to a "no such file" error when the appendix is typeset.

## Cause

The axp file is created as `\jobname.axp` at the time, when the `apxproof` is loaded, i.e. when `\usepackage{apxproof}` is expanded. When working with precompiled preambles, at that time `\jobname` is `document_preamble` instead of `document`.

If nothing else prevents it, the obvious fix would be to defer the initialization of the `.axp` file with an `\AtBeginDocument`.

**Comment by PierreSenellart** [comment]
Thanks for the issue, and for the fix! You taught me about this precompilation mechanism. This is a straightforward fix indeed, merged in (abede86) with a few minor corrections. Will be integrated into the next release (1.0.7), once I process all your other issues. :-)
