### ISSUE TITLE
Apxproof makes \section brittle

### ISSUE THREAD

**Issue by kbauer** [PierreSenellart/apxproof#22]
Apparently apxproof makes the `\section` command brittle.

With apxproof, using anything other than plain text becomes dangerous, leading to failure of e.g.

```
\documentclass{article}
\usepackage{apxproof}

\begin{document}

\section{A \textit{B}}

\end{document}
```

The source of the issue seems to be the line
```
\def\@section#1{%
  \global\edef\axp@sectitle{#1}%    <-- This one.
  ...
}
```

Other things that broke for me with `apxproof` when used in `\section` commands:

   - `\color{...}`
   - Various math formattings (e.g. `$\mathbf{P}$`).

**Comment by PierreSenellart** [comment]
Thanks for the bug report. Fixed in 6f6101e. The `\edef` was definitely misguided here.

**Comment by kbauer** [comment]
Simply removing `\edef` made some examples fail for me. Combined with #23, I created a pull request for a larger change that should fix both issues.

**Comment by PierreSenellart** [comment]
Yes, in addition to removing `\edef` you need to use `\expandonce` when writing `\axp@sectitle` to the `.apx` file, which is what we both did.
