### ISSUE TITLE
Feature Request: signal that a theorem will be repeated

### ISSUE THREAD

**Issue by fsikora** [PierreSenellart/apxproof#32]
Hello,

it could be nice to have something to signal that the proof of the theorem will be in the appendix (a star or something after its name), i.e. when the rep version is used.

**Comment by PierreSenellart** [comment]
There is already a (discrete) sign that a theorem is repeated: when hyperref is enabled, the number of the theorem becomes a hyperlink that points to the repeated theorem.

I do not want to have anything more visible by default, as the theorems should appear exactly as they would without the appendix. But I have added a customization command that you can set to whatever you like to add some material at the beginning of repeated theorems (for example, a margin note).

You can try this using the apxproof.sty from the develop branch: https://raw.githubusercontent.com/PierreSenellart/apxproof/develop/apxproof.sty 

An exemple of use is in: https://github.com/PierreSenellart/apxproof/blob/develop/examples/repeatedtheorem/test.tex

I should be releasing a new version including this feature within a couple of weeks.
