### ISSUE TITLE
Disable single-column mode for appendix

### ISSUE THREAD

**Issue by a3nm** [PierreSenellart/apxproof#4]
In some circumstances (e.g., camera-ready submissions which include an appendix), it is useful to leave the appendix in two-column mode. Would it be possible to have an option to do this?

**Comment by PierreSenellart** [comment]
This should now be possible with the option appendixcol=same, from the develop mode (commit  	1ac4b6e). Can you test?

**Comment by a3nm** [comment]
Seems to work, thanks!
