### ISSUE TITLE
Error with nested optional arguments in theorem-like environment defined by \newtheoremrep

### ISSUE THREAD

**Issue by komorin95** [PierreSenellart/apxproof#41]
Hi Pierre and contributors,
Thank you for maintaining such a useful style file!
I've just realized that the following code doesn't compile (with v1.2.1):
```
\documentclass{article}
\usepackage{apxproof}
\newtheoremrep{theorem}{Theorem}
\begin{document}
\begin{theoremrep}[{\cite[pp.\,9--44]{leunen}}]
	Some good theorem holds.
\end{theoremrep}
\begin{proof}
	Some technical proof shows it.
\end{proof}
\bibliographystyle{plain}
\bibliography{refs}
\end{document}
```
Here, the content of `refs.bib` is:
```
@book{leunen,
author = "Mary-Claire van Leunen",
title = "A Handbook for Scholars",
year = 1978,}
```
(It is taken from [this book in Japanese](https://gihyo.jp/book/2017/978-4-7741-8705-1) .)

Note that the following one compiles:
```
\documentclass{article}
\usepackage{apxproof}
\newtheoremrep{theorem}{Theorem}
\begin{document}
\begin{theorem}[{\cite[pp.\,9--44]{leunen}}]
	Some good theorem holds.
\end{theorem}
\begin{proof}
	Some technical proof shows it.
\end{proof}
\bibliographystyle{plain}
\bibliography{refs}
\end{document}
```
and so does the following one:
```
\documentclass{article}
\usepackage{apxproof}
\newtheoremrep{theorem}{Theorem}
\begin{document}
\begin{theoremrep}[\cite{leunen}]
	Some good theorem holds.
\end{theoremrep}
\begin{proof}
	Some technical proof shows it.
\end{proof}
\bibliographystyle{plain}
\bibliography{refs}
\end{document}
```
So I guess something is going wrong when `theoremrep` environment deals with an optional argument of a command in the optional argument of the `theoremrep` environment itself.
I'd appreciate it very much if this is resolved.
Thanks!

**Comment by komorin95** [comment]
I've just found a workaround.
The following compiles and works as expected:
```
\documentclass{article}
\usepackage{apxproof}
\newtheoremrep{theorem}{Theorem}
\begin{document}
\newcommand{\leunencite}{\cite[pp.\,9--44]{leunen}}
\begin{theoremrep}[\leunencite]
	Some good theorem holds.
\end{theoremrep}
\begin{proof}
	Some technical proof shows it.
\end{proof}
\bibliographystyle{plain}
\bibliography{refs}
\end{document}
```
So the nature of the problem might be like that of Issue #34.

I also noticed that the problem has actually nothing to do with `\cite`.
Indeed, the following doesn't compile:
```
\documentclass{article}
\usepackage{apxproof}
\newtheoremrep{theorem}{Theorem}
\newcommand{\cmd}[2][default]{#1#2}
\begin{document}
\begin{theoremrep}[{\cmd[arg1]{arg2}}]
	Some good theorem holds.
\end{theoremrep}
\begin{proof}
	Some technical proof shows it.
\end{proof}
\end{document}
```

**Comment by PierreSenellart** [comment]
Thanks for the bug report. This was an easy bug to fix, the latest version from the develop branch (commit 2b56903) should fix this. Another workaround is to add an extra level of braces within the optional argument of the repeated theorem.

**Comment by komorin95** [comment]
Thank you very much!
