### ISSUE TITLE
Appendix section number if using chapters

### ISSUE THREAD

**Issue by miguelbpgh** [PierreSenellart/apxproof#42]
Hello,

I would like to use the apxproof package in a document which is sectioned with chapters (and possibly parts). 

I would like all appendix sections generated by apxproof to be part of a chapter, let's say chapter "A", and then each section would be named "A.1 Proofs for Section ... ". What I'm obtaining instead is ".1 Proofs for Section ...".

Is there a workaround for this?

Here are pictures of the behaviour I'm obtaining as well as the code I'm using:
![image](https://user-images.githubusercontent.com/56127923/103667208-8d903580-4f6d-11eb-821c-4900a634e1ae.png)
![image](https://user-images.githubusercontent.com/56127923/103667254-97b23400-4f6d-11eb-8ff7-c495a8eeb74f.png)
![image](https://user-images.githubusercontent.com/56127923/103667273-9d0f7e80-4f6d-11eb-9ddc-fff1e21be0a5.png)

```
\documentclass{report}
\usepackage[utf8]{inputenc}

\usepackage[bibliography=common]{apxproof}

\BeforeBeginEnvironment{appendices}{\edef\TheChapter{\thechapter}}
\AtBeginEnvironment{appendices}{\renewcommand\thesection{\TheChapter.\Alph{section}}}

\renewcommand{\appendixprelim}{
    \clearpage\onecolumn
    \appendix\chapter{Proofs of the theorems in the main text}
    %\section{testsection}
}

\usepackage{amsthm}

\theoremstyle{plain}
    \newtheoremrep{theorem}{Theorem}[chapter]

\usepackage{hyperref}
    \hypersetup{
        bookmarksnumbered=true,
        colorlinks=true,
        linkcolor=blue
    }

\begin{document}

\tableofcontents

\chapter{the first chapter}

\section{the first section}
\begin{toappendix}
    \label{apx:the first section}
\end{toappendix}

\begin{theoremrep}
    This is a theorem.
\end{theoremrep}
\begin{inlineproof}
    See \ref{apx:the first section}.
\end{inlineproof}
\begin{proof}
    This is the actual proof of the theorem, which will show up in the appendix.
\end{proof}

\end{document}
```

**Comment by PierreSenellart** [comment]
This is because `\appendixprelim` is executed before the `\appendix` command. So there will be two `\appendix` in a row, and the `chapter` counter will be reset.

I suggest the following instead, which adds the `\chapter` command just after the `\appendix` command, and does not require any change to `apxproof`: 
```
\renewcommand{\appendixprelim}{\clearpage\onecolumn}
\apptocmd{\appendix}{\chapter{Proofs of the theorems in the main text}}{}{}
```

**Comment by miguelbpgh** [comment]
Thanks! For the answer and the package.
