### ISSUE TITLE
Compatibility with claimproof (lipics)

### ISSUE THREAD

**Issue by fsikora** [PierreSenellart/apxproof#49]
LIPICS provide the fancy claimproof environement, allowing to have proofs inside a larger proof. 
However, apxproof doesn't redefine it, and thus not putting the proof of a "claimrep" in the appendix.

MWE :

```
\documentclass[a4paper,UKenglish,cleveref]{lipics-v2021}
\usepackage{apxproof} 
\newtheoremrep{theorem}{Theorem}
\newtheoremrep{claim}[theorem]{Claim}

\begin{document}

\begin{claimrep}Claimrep with classical proof env : OK
\end{claimrep}
\begin{proof}
proof
\end{proof}

\begin{claimrep}Claimrep with claimproof env : KO
\end{claimrep}
\begin{claimproof}
proof
\end{claimproof}

\begin{claim}Classical Claim with claimproof. 
\end{claim}
\begin{claimproof}
proof
\end{claimproof}

\end{document}
```

**Comment by PierreSenellart** [comment]
I added such support in 8f32546; can you try the latest `apxproof.sty` from the develop branch (at https://raw.githubusercontent.com/PierreSenellart/apxproof/develop/apxproof.sty )? If this works for you, I will do a new release with this fix.

**Comment by fsikora** [comment]
It works, thanks!
