### ISSUE TITLE
Use common bibliography in appendix and main text

### ISSUE THREAD

**Issue by a3nm** [PierreSenellart/apxproof#5]
Continuing on the (purely hypothetical) use case of camera-ready submissions which include an appendix, in this case it is a waste of space to have the same references both in the appendix and in the main bibliography.

Would it be possible to have a setting to use the main bibliography for both the main text and appendix?

Thanks!

**Comment by PierreSenellart** [comment]
This should now be possible with the option bibliography=separate, from the develop branch (commit 1ac4b6e). Can you test?

**Comment by a3nm** [comment]
I guess you mean `bibliography=common`. This seems to work fine, thanks!
