### ISSUE TITLE
Feature request: add a hook after the appendix

### ISSUE THREAD

**Issue by vikraman** [PierreSenellart/apxproof#51]
While submitting my thesis, I needed to add a CV after the appendix, and I had to modify apxproof to allow me to insert it after the generated appendix. It would be nice if such a hook was provided. What I did was add an `\appendixpost` similar to `\appendixprelim`, and then used it like this.

```latex
\renewcommand{\appendixpost}{
  \addtocontents{toc}{%
    \protect\contentsline{chapter}{Curriculum Vitae}{}{}{}}
  \includepdf[pages=-]{cv.pdf}
}
```

**Comment by PierreSenellart** [comment]
There is also the option of putting the content in question within a `toappendix` environment at the end of the document. Anything wrong with this option?

**Comment by vikraman** [comment]
I did try `toappendix` but that automatically generates a new section.

**Comment by jacob-roth** [comment]
Similarly, is there a way to `\label{}` the `apxproof`-generated appendix so that it can be `\cref{}`ed? For example, I asked a question [here](https://tex.stackexchange.com/questions/687806/refer-to-appendix-in-apxproof)

**Comment by PierreSenellart** [comment]
You can use:

```latex
\begin{toappendix}
  \label{apx:delayed_proofs}
\end{toappendix}
```

at any location that will be put in the corresponding section (in your example, for instance, you could put it just after the `\section{Test}` line). Just tested it, the interaction with `cleveref` works fine.

**Comment by PierreSenellart** [comment]
Closing this issue, as an `\appendixpost` hook can be simulated just by using the `toappendix` environment at the apprioriate location.
