### ISSUE TITLE
Customize the section title generated by apxproof

### ISSUE THREAD

**Issue by Yutong-Dai** [PierreSenellart/apxproof#52]
Hi @PierreSenellart,
Thanks for the great package!
I would like to know if it is possible to create something like the screenshot below, which has more fine-grained control over the titles auto-generated by `apxproof` package. You will notice that
1. The proofs in the appendix have a shared "upper-level" section title `Deferred Proofs``. 
2. The title for each subsection in the appendix actually corresponds to the subsection title in the main text. For example, `Proofs for  Section 1.1: Analysis for Case I` in the appendix versus `Analysis for Case I` in the main text.

<img width="1287" alt="image" src="https://user-images.githubusercontent.com/19240875/234095425-28f7d8ac-df04-4334-8c75-4c71b71867e0.png">

However, using `apxproof` package, I can only now generate something like the screenshot below. Specifically,

1. I don't know how to create the shared main title `Deferred Proofs``. 
2. I don't have fine-grained control over the generated title.

<img width="1250" alt="image" src="https://user-images.githubusercontent.com/19240875/234096281-c2f92e5c-c974-4b5c-ae80-c037a6c204d4.png">

I tried to play around with `\appendixsectionformat` option; however, from [the code](https://github.com/PierreSenellart/apxproof/blob/57b421356aacc913762747d292cbe88e410d2015/apxproof.sty#L134) it seems that the package only uses the title Information up to the `section` level instead of `subsection` or even `subsubsection` levels.

Thanks,
YD

---
The latex code (compiled on Overleaf for the desired output, i.e., the first screenshot) is attached below.

```latex
\documentclass{article}
\usepackage[appendix=append,forwardlinking=no]{apxproof}
\newtheoremrep{theorem}{Theorem}
\date{}
\title{apxproof: Flexible Title}


\begin{document}

\maketitle

\section{Analysis}
\subsection{Analysis for Case I}
\begin{theorem}\label{thm:1}
We assert that
$$
1+1 = 2
$$
\end{theorem}


\subsection{Analysis for Case II}
\begin{theorem}\label{thm:2}
We assert that
$$
2+2 = 4
$$
\end{theorem}

\appendix
\newpage
\section{Deferred Proofs}
\subsection{Proofs for  Section 1.1: Analysis for Case I}
\paragraph{Theorem~\ref{thm:1}
We assert that
$$
1+1 = 2
$$
}
\begin{proof}
This is trivial(1).
\end{proof}
\subsection{Proofs for  Section 1.2: Analysis for Case II}
\paragraph{Theorem~\ref{thm:2}
We assert that
$$
2+2 = 4
$$
}
\begin{proof}
This is trivial(2).
\end{proof}
\end{document}
```

The latex code for generating the second screenshot is also attached.

```latex
\documentclass{article}
\usepackage[appendix=append,forwardlinking=no]{apxproof}
\newtheoremrep{theorem}{Theorem}
\date{}
\title{apxproof test}


\begin{document}

\maketitle

\section{Analysis}
\subsection{Analysis for Case I}
\begin{theoremrep}
$$
1+1 = 2
$$
\end{theoremrep}
\begin{proof}
This is trivial(1).
\end{proof}

\subsection{Analysis for Case II}
\begin{theoremrep}
$$
2+2 = 4
$$
\end{theoremrep}
\begin{proof}
This is trivial(2).
\end{proof}


\end{document}

```

**Comment by PierreSenellart** [comment]
Hi,

Thanks for your comment and interest. There is no automatic way to do this, though you can do it semi-manually easily enough:

```latex
\documentclass{article}
\usepackage[appendix=append]{apxproof}
\newtheoremrep{theorem}{Theorem}
\date{}
\title{apxproof test}


\begin{document}

\begin{toappendix}
  \section{Deferred Proofs}
\end{toappendix}

\maketitle

\section{Analysis}
\nosectionappendix
\subsection{Analysis for Case I}
\label{case1}
\begin{toappendix}
  \subsection{Proofs for Section~\ref{case1}: Analysis for Case I}
\end{toappendix}

\begin{theoremrep}
$$
1+1 = 2
$$
\end{theoremrep}
\begin{proof}
This is trivial(1).
\end{proof}

\subsection{Analysis for Case II}
\label{case2}
\begin{toappendix}
  \subsection{Proofs for Section~\ref{case1}: Analysis for Case II}
\end{toappendix}

\begin{theoremrep}
$$
2+2 = 4
$$
\end{theoremrep}
\begin{proof}
This is trivial(2).
\end{proof}


\end{document}
```

Is this what you want? I could try improve the customization options so that it can be done automatically, but I am not sure what a good interface would be in the general case.

**Comment by Yutong-Dai** [comment]
Thanks, this is exactly what I want. I'm not sure how to automate this part.
```latex
\begin{toappendix}
  \section{Deferred Proofs}
\end{toappendix}
```
But I think it might be possible to automate the following by providing something like to `\tocdepth{(a number)}`. 
```latex
\begin{toappendix}
  \subsection{Proofs for Section~\ref{case1}: Analysis for Case I}
\end{toappendix}

\begin{toappendix}
  \subsection{Proofs for Section~\ref{case2}: Analysis for Case II}
\end{toappendix}
```
Specifically, `\tocdepth{1}` has the default behavior of `apxproof`, where the section title in the appendix inherits the corresponding section title in the main text and `\tocdepth{2}` makes it inherits the corresponding subsection title.

Again, thanks for the timely response.

**Comment by PierreSenellart** [comment]
Thanks for the suggestion, I'll see if I have the time to implement something like this.
