### ISSUE TITLE
Disable the page break before appendix

### ISSUE THREAD

**Issue by a3nm** [PierreSenellart/apxproof#6]
It could be useful also if the `\clearpage` added before the appendix could be disabled. (I don't know whether having an option for this is reasonable, or whether there should be a more generic mechanism to configure what gets issued before the appendix starts.)

**Comment by PierreSenellart** [comment]
I have replaced the tentative `appendixcol` option introduced to fixed #4 for a more flexible approach using a `\appendixprelim` command that can be redefined. By default this command is defined as:
`\newcommand{\appendixprelim}{\clearpage\onecolumn}`. Disabling pagebreak, single-column mode, etc., or styling the appendix differently can be done by simply redefining this command with `\renewcommand`.

Please test, commit cc4f0cb of [branch develop](/PierreSenellart/apxproof/tree/develop).

**Comment by a3nm** [comment]
Works for me, and I think this is a reasonable approach; thanks!
