### ISSUE TITLE
Weird issue with parentheses in optional arguments to theorems

### ISSUE THREAD

**Issue by a3nm** [PierreSenellart/apxproof#8]
Trying to compile the file [ecm.zip](https://github.com/PierreSenellart/apxproof/files/1145352/ecm.zip) gives a weird error:

```
apxproof: Appendix material appended to the document
apxproof: Separate bibliography for appendix material) (./ecm.aux)

LaTeX Warning: Citation `a' on page 1 undefined on input line 10.

! Incomplete \iffalse; all text was ignored after line 10.
<inserted text> 
                \fi 
l.10 \end{theoremrep}
                     
? 
```

The presence of the opening parenthesis in the optional argument to the theoremrep appears to be important, as it works fine without it. Adding a closing parenthesis does not help. Any idea what can be going on?

**Comment by PierreSenellart** [comment]
I was not correctly protecting the optional arguments of theorems when writing to the appendix file. Should be fixed in d08af94c81842e4c868355f257fd4eb61ddecd45. Can you test with https://raw.githubusercontent.com/PierreSenellart/apxproof/develop/apxproof.sty on real documents?

**Comment by a3nm** [comment]
This seems to work fine on the paper where the problem was showing up. Thanks a lot!

**Comment by PierreSenellart** [comment]
Unsurprising that the error was different, all kinds of error could be produced by this (incorrect timing of the evaluation of whatever was within the optional argument). I will not release 1.0.6 right now, waiting to test with a wide variety of documents first.
